- id: golangci-lint
  name: golangci-lint
  description: Fast linters runner for Go.
  entry: golangci-lint run --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: golangci-lint-diff
  name: golangci-lint-diff
  description: Fast linters runner for Go. Only runs on changed files.
  entry: golangci-lint run --new-from-rev HEAD --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
