- id: golangci-lint
  name: golangci-lint
  description: Fast linters runner for Go.
  entry: golangci-lint run --new-from-rev HEAD --fix
  require_serial: true
  types: [go]
  language: golang
  pass_filenames: true
