[context.production.environment]
  GO_VERSION = "1.18"
  NODE_VERSION = "17"
#   NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERSION = "8.5.5"

[context.deploy-preview.environment]
  GO_VERSION = "1.18"
  NODE_VERSION = "17"
#   NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERSION = "8.5.5"

[context.branch-deploy.environment]
  GO_VERSION = "1.18"
  NODE_VERSION = "17"
#   NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERSION = "8.5.5"
