version: v1.56.2
name: custom-golangci-lint # optional, default: gcl-custom
destination: ./my/path/    # optional, default: .
plugins:
  # a plugin from a Go proxy
  - module: 'github.com/example/plugin3'
    version: v1.2.3

  # a plugin from a Go proxy (with a specific import path)
  - module: 'github.com/example/plugin4'
    import: 'github.com/example/plugin4/foo'
    version: v1.0.0

  # a plugin from local source (with absolute path)
  - module: 'github.com/example/plugin2'
    path: /my/local/path/plugin2

  # a plugin from local source (with relative path)
  - module: 'github.com/example/plugin1'
    path: ./my/local/path/plugin1

  # a plugin from local source (with absolute path and a specific import path)
  - module: 'github.com/example/plugin2'
    import: 'github.com/example/plugin4/foo'
    path: /my/local/path/plugin2
