---
name: PR build
on:
  push:
#    branches:
#      - master
  pull_request:
jobs:
  build:
    env:
      GIT_TAG: v1.26.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        golang:
          - 1.12
          - 1.13
          - 1.14
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.golang }}
      - name: Check if README.md is up to date
        run: time make fast_check_generated
      - name: Run tests
        run: make test

