---
name: PR build
on:
  push:
#    branches:
#      - master
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        golang:
          - 1.12
          - 1.13
          - 1.14
        os:
          - windows-latest
          - ubuntu-latest
          - macos-lates
    steps:
      - uses: actions/checkout@v2
      - name: Check if README.md is up to date
        run: time make fast_check_generated
      - name: Run tests
        run: >
          docker run -t
          -v ${{ github.workspace }}:/go
          golang:${{ matrix.golang }}
          time make tests

